// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.user_id", "2873306a-3126-49ba-bb67-3fdf1b11adc1");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1558597988);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1558598108);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1558714495);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1558662548);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1558714615);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1558597868);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1558598348);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1558598228);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 798720);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1558597479);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 77);
user_pref("browser.newtabpage.activity-stream.impressionId", "{4234bce5-37e4-43f5-9fac-3418fcd38049}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1558594800);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1558614309832");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1558616133832");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1558628779937");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1558632379937");
user_pref("browser.search.region", "IN");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1558597485");
user_pref("browser.slowStartup.averageTime", 13530);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20190215001400");
user_pref("browser.startup.homepage_override.mstone", "65.0.1");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1558597525509");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "65.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "2f7e07c915114bbc86c5610ce8e3c1e1");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 28);
user_pref("extensions.getAddons.cache.lastUpdate", 1558597998);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "65.0.1");
user_pref("extensions.lastPlatformVersion", "65.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"582ad36a-9da2-4b7c-a8e5-2944c59b105f\",\"screenshots@mozilla.org\":\"56792973-6a98-46de-9bef-74a13bc2aea3\",\"webcompat-reporter@mozilla.org\":\"9519c2df-3b68-4c96-bb64-9204e4a93521\",\"webcompat@mozilla.org\":\"e2a0463d-c26f-4b69-99c7-6097fa7d3f54\",\"fxmonitor@mozilla.org\":\"b10da5a8-102b-4e0b-9a88-356b2e4a8a6c\",\"baidu-code-update@mozillaonline.com\":\"f327fec7-aa66-4211-949a-fe99072c909b\"}");
user_pref("font.internaluseonly.changed", true);
user_pref("idle.lastDailyNotification", 1558598095);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1558597764);
user_pref("media.gmp-gmpopenh264.version", "1.6");
user_pref("media.gmp-manager.buildID", "20190215001400");
user_pref("media.gmp-manager.lastCheck", 1558597732);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1558598095);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "64b5c0d5-4801-4af6-bc99-2c7564b91dfc");
user_pref("security.sandbox.plugin.tempDirSuffix", "b83d4303-ad68-4de1-ad02-c240a324382a");
user_pref("services.blocklist.addons.checked", 1558597888);
user_pref("services.blocklist.gfx.checked", 1558597888);
user_pref("services.blocklist.onecrl.checked", 1558597888);
user_pref("services.blocklist.pinning.checked", 1558597888);
user_pref("services.blocklist.plugins.checked", 1558597888);
user_pref("services.settings.clock_skew_seconds", 6);
user_pref("services.settings.last_update_seconds", 1558597888);
user_pref("services.settings.main.language-dictionaries.last_check", 1558597888);
user_pref("services.settings.main.onboarding.last_check", 1558597888);
user_pref("services.settings.main.sites-classification.last_check", 1558597888);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1558598095);
user_pref("toolkit.startup.last_success", 1558597470);
user_pref("toolkit.telemetry.cachedClientID", "6beca98f-5034-45cc-83f5-59515b2e8e3b");
user_pref("toolkit.telemetry.previousBuildID", "20190215001400");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
